name: bar

on:
  workflow_dispatch:
  push:
    paths:
      - "bar/**"
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: event
        run: |-
          cat <<EOF | jq . --sort-keys
          ${{ toJson(github) }}
          EOF

      - name: Run bar script
        run: echo "Running bar script..."

