name: foo

on:
  workflow_dispatch:
  push:
    paths:
      - "foo/**"
jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: event
        run: |-
          cat <<EOF | jq . --sort-keys
          ${{ toJson(github) }}
          EOF

      - name: Run foo script
        run: echo "Running foo script..."

